# ==========================================
# üèüÔ∏è CONFIGURACI√ìN DEL √ÅRBITRO (GREEN AGENT)
# ==========================================
[green_agent]
# ID DEL GREEN (CapsBench)
agentbeats_id = "019c0c11-ce03-77e0-91b3-fa958206b1fc"
# Aqu√≠ le pasamos la API KEY segura de GitHub al contenedor
env = { GOOGLE_API_KEY = "${GOOGLE_API_KEY}", SERVER_URL = "http://green-agent:9009" }
# Configuraci√≥n del entorno (Puerto y Logs)
env = { PORT = "9009", LOG_LEVEL = "INFO" }


# ==========================================
# üü£ CONFIGURACI√ìN DEL JUGADOR (PURPLE AGENT)
# ==========================================
[[participants]]
# ID DEL PURPLE
agentbeats_id = "019c0b17-335b-7553-8b43-81d097bb5387"
name = "purple_agent"


# ==========================================
# ‚öôÔ∏è REGLAS DE SEGURIDAD
# ==========================================
[config]
# Seguro de vida: Si la partida se cuelga, GitHub la corta a los 100 turnos.
max_turns = 100

